### PR TITLE
Fix an issue where logout btn. was always visible

### LINKED ISSUE #49: Ensure Logout button isn't visible in the login page.
The common header always displays a logout button.
Since we display this header everywhere, we should make sure we don't provide a logout button to click when the user is already logged out and looking at the login page.

### PR DESCRIPTION
**Pull request by StasTserk**
Fixes an issue where the logout button was always visible in the header even when the user hadn't logged in yet.

Uses a context provider to share state about logged in status between the logon page (which can modify it) and the header (which can modify and consumes it)

Also fixes some minor inaccuracies with how we were clearing cookies.

Resolves #49

### CODE REVIEW

File: src/client/pages/PageRouter.tsx [hunk 1]
```diff
@@ -4,11 +4,28 @@ import { HomePage } from './HomePage';
...
+});
+
+interface UserContext {
+    loggedIn: boolean;
+    setLoggedIn: (v: boolean) => void;
+}
 
 export const PageRouter = (): JSX.Element => {
+    const authContext = useContext(AuthContext);
+    const [loggedIn, setLoggedIn] = useState(document.cookie.indexOf('jwtToken') !== -1);
```
Comment (StasTserk) [inline src/client/pages/PageRouter.tsx:23]: `document.cookie.indexOf('jwtToken') !== -1` is the wrong thing to do here, but for now it gets the job done.
Presumably we'll want the user object to live in this auth context, but we'll need to expand our auth api to support that in the future.

File: src/server/api/AuthenticationApi.ts [hunk 2]
```diff
@@ -48,7 +48,7 @@ export class AuthenticationApi {
                         const { id } = decodedToken.payload;
                         this._userStore.revokeToken(token, id);
                     }
-                    response.cookie('jwtToken', undefined);
+                    response.clearCookie('jwtToken');
```
Comment (StasTserk) [inline src/server/api/AuthenticationApi.ts:51]: the original method was leaving the cookie as `jwtToken='undefined'` which is not the same as clearing it.

File: src/client/pages/PageRouter.tsx [hunk 3]
```diff
@@ -4,11 +4,28 @@ import { HomePage } from './HomePage';
...
 import { Login } from './Login';
 import { Header } from '../components/Header';
+import { useContext, useState } from 'react';
+
+export const AuthContext = React.createContext<UserContext>({
+    loggedIn: false,
+    setLoggedIn: () => {
+        return;
+    },
+});
```
Comment (StasTserk) [inline src/client/pages/PageRouter.tsx:14]: If we have complicated enough state to manage, contexts might be justified in taking up a file on their own in some sort of `contexts` folder, but for now it's packed in with `PageRouter` which is the closest common parent of elements that need to consume it.

Also, if our application state ends up being sufficiently complex, might be worth looking into `react-redux` for managing it?

Comment (mzixu) [reply src/client/pages/PageRouter.tsx:14]: I agree, I want to stay away from react-redux until we get to a point where we actually want to take advantage of it.

File: src/client/pages/PageRouter.tsx (hunk 1 above)
Comment (mzixu) [reply src/client/pages/PageRouter.tsx:23]: Yes, good thing you left this here 🐱 maybe we should leave a comment on this line in the actual code to indicate this intent. I feel like we may forget about this.

Comment (StasTserk) [reply src/client/pages/PageRouter.tsx:23]: I think when we go to deal with this, instead of having a `loggedIn` boolean, we'll have a `user` User object to be able to pull data from. the logic will instantly swap there from checking the cookie to just checking the user state for null.

(all this to say it'll take care of itself when we upgrade the functionality)

Comment (mzixu) [reply src/client/pages/PageRouter.tsx:23]: actually, i misunderstood, cuz my js is not great lol. Sure for now, not finding the jwtToken in the cookie is fine.

**Review by mzixu — APPROVED** [review]
👍 looks good to me
